name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.8.5
        
    - name: Install dependencies
      run: pip install -r requirements/dev.txt
    
    - name: Run check
      run: make build-doc
