name: Makefile CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v3.1.2
      with:
        python-version: 3.8.5
        
    - name: Install dependencies
      run: pip install -r requirements/dev.txt
    
    - name: Run check
      run: make build-doc
      
    - name: Git config user
      uses: snow-actions/git-config-user@v1.0.0
      with:
        name: ${{ github.actor }}
        email: action@github.com
      
    - name: Publish on branch
      run: |
        rm -rf /tmp/public && mv public /tmp/public
        git checkout documentation || (git checkout --orphan documentation && rm -rf *)
        echo "<meta http-equiv="refresh" content="0; URL=${GITHUB_REF#refs/tags/}" />" > index.html
        mv /tmp/public ${GITHUB_REF#refs/tags/}
        git add .
        git commit -m "Release documentation for version ${GITHUB_REF#refs/tags/}"
        git push -u origin documentation
